### ISSUE TITLE
Add test suite for foundry?

### ISSUE THREAD

**Issue by shunkakinoki** [CodeforDAO/contracts#4]
I've come to really dig [Foundry](https://github.com/foundry-rs/foundry) for all purposes testing
Would you mind if i create a test suite to demonstrate its capabilities?
It's really fast. Writing tests in solidity makes you feel like a magician without any context swtiching required

**Comment by guo-yu** [comment]
A long time ago I opened a branch https://github.com/CodeforDAO/contracts/tree/migrate_to_foundry 
Basically the work was delayed by Cairo and other projects.
It would be great if you plan to continue writing this branch!

**Comment by shunkakinoki** [comment]
Sorry for the late reply - on track to do the above this weekends!

**Comment by shunkakinoki** [comment]
Doing updates in #6

**Comment by shunkakinoki** [comment]
Closing this for now- believe all test cases were added with #7
